#!/bin/sh

# Shamelessly pilfered from https://stackoverflow.com/a/49265008
formatter=$(which cfbs)

if [ -z "$formatter" ]; then
  1>&2 echo "$formatter not found. Pre-commit formatting will not be done."
  exit 0
fi

git show ":cfbs.json" > "tmp.cfbs.json"
echo "Formatting cfbs.json"
"$formatter" pretty tmp.cfbs.json
hash=$(git hash-object -w "tmp.cfbs.json")
git update-index --add --cacheinfo 100644 "$hash" "cfbs.json"
rm "tmp.cfbs.json"
ret=0
